development:
  adapter: postgresql
  database: anagram_development
  pool: 5
  host: localhost
  username: 
  password: 
    
test:
  adapter: postgresql
  database: anagram_test
  pool: 5
  host: localhost
  username: 
  password: 
  
production:
  url: <%= ENV['DATABASE_URL'] %>